Fixup debugDispatcher
Without changing `lint-staged`:

```
✖ tsc --noEmit --target 'es2016':
src/debugger/debugDispatcher.ts(2,45): error TS2792: Cannot find module '@vscode/debugadapter'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
```

not easy to find details here, just going to `tsc` the whole project since it's still pretty speedy.