Revert changes that broke debugger in 2.8.3 (#171)
* Revert "Add ESLint and fix problems"

This reverts commit 0f9d15f0ca9f8ef94796b1e8188ea20ded2e8672.

* Remove noise from sample test

* Use typescript~4.7.4

TypeScript does not use semantic versioning. See https://github.com/Microsoft/TypeScript/issues/14116

* Install ESLint and add warning notifications

* Fixup some ESLint warnings

* Lint all src files

* Fixup codeUtil.ts

* Ensure no warnings when committing

* Change script  to  for clarity

* Fixup codeUtil.ts

* Fixup fileManager and runnerService

```
$ npx tsc --noEmit --project tsconfig.json src/common/fileManager.ts
error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

oh well

* Fixup global.ts

* Fixup debugDispatcher

Without changing `lint-staged`:

```
✖ tsc --noEmit --target 'es2016':
src/debugger/debugDispatcher.ts(2,45): error TS2792: Cannot find module '@vscode/debugadapter'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
```

not easy to find details here, just going to `tsc` the whole project since it's still pretty speedy.

* Update Contributing.md

* Fixup debugServer

* Fixup debugSession

* Fixup breakpointHandler and variableHandler

* Fixup model

* Fixup parser.ts

* Fixup ahkHoverProvider

* Fixup some providers

* Fixup formattingProvider

Keep known issue #40 to minimize merge conflicts with #163

* Fixup signatureProvider

* Use Prettier 2.6.1

Matches https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode used in changelog, see also https://prettier.io/docs/en/install.html#:~:text=Even%20a%20patch%20release%20of%20Prettier%20can%20result%20in%20slightly%20different%20formatting "Even a patch release of Prettier can result in slightly different formatting"

* Misc fixups

* Update enum member names to match convention

* Fixup Continue enum names